[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32 @ 6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
    -DCORE_DEBUG_LEVEL=3

lib_deps =
    jvpernis/PS3 Controller Host @ ^1.1.0
    crankyoldgit/IRremoteESP8266 @ ^2.8.0
